name: CI Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  build-and-push:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: 'src/python-app'
        sparse-checkout-cone-mode: false

    - name: Move app files to root
      run: |
        shopt -s dotglob
        mv src/python-app/* .
        rm -rf src

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ghcr.io/${{ github.repository }}/python-app:test_tag

    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ github.repository }}/python-app:test_tag
        trivy-config: trivy.yaml
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Create release
      id: release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor
        tag_prefix: ''
        release_name: "Release <RELEASE_VERSION>"

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/python-app:latest
          ghcr.io/${{ github.repository }}/python-app:${{ steps.release.outputs.tag_name }}
